fix nil pointer panic when changing bucket config
kube-object-storage/lib-bucket-provisioner pull request #222
Opened 2022-08-09 16:08 UTC by degorenko

Related-Issue: https://github.com/kube-object-storage/lib-bucket-provisioner/issues/219

Signed-off-by: Denis Egorenko <degorenko@mirantis.com>

2022-08-10 16:45 UTC, BlaineEXE requested changes

2022-08-10 16:45 UTC, BlaineEXE commented on pkg/provisioner/controller.go
> +		destAdditionalConfig = srcAdditionalConfig
I'm not sure if this is the source of the issue, but the copy must be a deep copy.

```suggestion
	if destAdditionalConfig != nil {
		for key, _ := range destAdditionalConfig {
			delete(destAdditionalConfig, key)
		}
	}
	for key, value := range srcAdditionalConfig {
		destAdditionalConfig[key] = value
	}
```

2022-08-11 16:22 UTC, BlaineEXE commented
I think this looks good. Would you describe the manual tests you used to test that the fix is working? I'd like to make sure there aren't any corner cases missed

2022-08-11 16:28 UTC, degorenko commented
@BlaineEXE  so, i did fork, made changes. But i'm currently using Rook 1.8.5, so i have to rebase on commit which is used in go.mod for 1.8.5 version. Finally, i have v0.0.0-20220105185820-c1da9586e05b plus that changes on top of it (I have additional config-override-1.8 branch in fork). Replaced in Rook go.mod l-b-p dependency on my fork commit, built Rook image on top of it and then test. So in my tests Rook 1.8.5+current change. Does it suites your expectations ?

2022-08-11 16:31 UTC, BlaineEXE commented
I was thinking to look at the logs and make sure...
- create OBC successful
- no changes to OBC (restart operator), nothing happens
- change OBC additional config, changes happen correctly now
- change another OBC field, controller errors saying it can't be updated
- delete OBC works

2022-08-11 16:55 UTC, degorenko commented
[rook-operator.log](https://github.com/kube-object-storage/lib-bucket-provisioner/files/9310460/rook-operator.log)
[user-stats.log](https://github.com/kube-object-storage/lib-bucket-provisioner/files/9310462/user-stats.log)

2022-08-11 16:56 UTC, degorenko commented
log contains some debug message around OBC spec diff, but it is not in current change, only for test purpose.

2022-08-11 18:48 UTC, BlaineEXE commented
The tests look great. Thank you. I'm trying to figure out why the CI is failing though.

2022-08-11 18:56 UTC, BlaineEXE commented
It looks like one of the tools used in CI is no longer hosted at the location. 

This line in travis.yml needs updated: https://github.com/kube-object-storage/lib-bucket-provisioner/blob/4bea5edaff58c0e80e3ad0c56f2894a7d456cc87/.travis.yml#L18 

Replacing that with this should get it going again I think.
```
curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/v1.16.0/install.sh | sh -s -- -b $(go env GOPATH)/bin && golangci-lint --version
```

2022-08-11 19:25 UTC, BlaineEXE approved these changes

2022-08-11 19:26 UTC, merged

2022-08-11 19:27 UTC, BlaineEXE commented
Merged. To pull the change into Rook, we just need a PR that updates the go.mod to use the latest version (hash) of this library. And we can have it backported back to 1.8 and 1.9 as well. 👍 Thanks again!